# Generated by Django 3.1.2 on 2020-10-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='titile',
            new_name='title',
        ),
    ]
